import 'package:flutter/cupertino.dart';
import 'package:provider_app/constant/configs.dart';
import 'package:provider_app/model/repository/skill_repository.dart';

class Armor {

  final int id;
  String armorName;
  int firstSkillId;
  String firstSkillName;
  int firstSkillLevel;
  int secondSkillId;
  String secondSkillName;
  int secondSkillLevel;
  int thirdSkillId;
  String thirdSkillName;
  int thirdSkillLevel;
  int fourthSkillId;
  String fourthSkillName;
  int fourthSkillLevel;
  int fifthSkillId;
  String fifthSkillName;
  int fifthSkillLevel;
  int minDefensePower;
  int maxDefensePower;
  int part;
  int firstSlot;
  int secondSlot;
  int thirdSlot;
  int hyakuryuSlot;
  int fireResistance;
  int waterResistance;
  int lightningResistance;
  int iceResistance;
  int dragonResistance;
  int grade;
  final DateTime createdAt;
  DateTime updatedAt;

  Armor(
      {
        this.id,
        this.armorName,
        this.firstSkillId,
        this.firstSkillName,
        this.firstSkillLevel,
        this.secondSkillId,
        this.secondSkillName,
        this.secondSkillLevel,
        this.thirdSkillId,
        this.thirdSkillName,
        this.thirdSkillLevel,
        this.fourthSkillId,
        this.fourthSkillName,
        this.fourthSkillLevel,
        this.fifthSkillId,
        this.fifthSkillName,
        this.fifthSkillLevel,
        this.minDefensePower,
        this.maxDefensePower,
        this.part,
        this.firstSlot,
        this.secondSlot,
        this.thirdSlot,
        this.hyakuryuSlot,
        this.fireResistance,
        this.waterResistance,
        this.lightningResistance,
        this.iceResistance,
        this.dragonResistance,
        this.grade,
        this.createdAt,
        this.updatedAt
      }
      );

  factory Armor.fromMap(Map<String, dynamic> json) => Armor(
      id: json['id'] as int,
      armorName: json['armorName'] as String,
      firstSkillId: json['firstSkillId'] as int,
      firstSkillName: json['firstSkillName'] as String,
      firstSkillLevel: json['firstSkillLevel'] as int,
      secondSkillId: json['secondSkillId'] as int,
      secondSkillName: json['secondSkillName'] as String,
      secondSkillLevel: json['secondSkillLevel'] as int,
      thirdSkillId: json['thirdSkillId'] as int,
      thirdSkillName: json['thirdSkillName'] as String,
      thirdSkillLevel: json['thirdSkillLevel'] as int,
      fourthSkillId: json['fourthSkillId'] as int,
      fourthSkillName: json['fourthSkillName'] as String,
      fourthSkillLevel: json['fourthSkillLevel'] as int,
      fifthSkillId: json['fifthSkillId'] as int,
      fifthSkillName: json['fifthSkillName'] as String,
      fifthSkillLevel: json['fifthSkillLevel'] as int,
      minDefensePower: json['minDefensePower'] as int,
      maxDefensePower: json['maxDefensePower'] as int,
      part: json['part'] as int,
      firstSlot: json['firstSlot'] as int,
      secondSlot: json['secondSlot'] as int,
      thirdSlot: json['thirdSlot'] as int,
      hyakuryuSlot: json['hyakuryuSlot'] as int,
      fireResistance: json['fireResistance'] as int,
      waterResistance: json['waterResistance'] as int,
      lightningResistance: json['lightningResistance'] as int,
      iceResistance: json['iceResistance'] as int,
      dragonResistance: json['dragonResistance'] as int,
      grade: json['grade'] as int,
      createdAt: DateTime.parse(json['createdAt'] as String).toLocal(),
      updatedAt: DateTime.parse(json['updatedAt'] as String).toLocal()
  );

  factory Armor.fromApiMap(Map<String, dynamic> json) => Armor(
      id: json['id'] as int,
      armorName: json['armor_name'] as String,
      firstSkillId: json['first_skill_id'] as int,
      firstSkillName: json['first_skill_name'] as String,
      firstSkillLevel: json['first_skill_level'] as int,
      secondSkillId: json['second_skill_id'] as int,
      secondSkillName: json['second_skill_name'] as String,
      secondSkillLevel: json['second_skill_level'] as int,
      thirdSkillId: json['third_skill_id'] as int,
      thirdSkillName: json['third_skill_name'] as String,
      thirdSkillLevel: json['third_skill_level'] as int,
      fourthSkillId: json['fourth_skill_id'] as int,
      fourthSkillName: json['fourth_skill_name'] as String,
      fourthSkillLevel: json['fourth_skill_level'] as int,
      fifthSkillId: json['fifth_skill_id'] as int,
      fifthSkillName: json['fifth_skill_name'] as String,
      fifthSkillLevel: json['fifth_skill_level'] as int,
      minDefensePower: json['min_defense_power'] as int,
      maxDefensePower: json['max_defense_power'] as int,
      part: json['part'] as int,
      firstSlot: json['first_slot'] as int,
      secondSlot: json['second_slot'] as int,
      thirdSlot: json['third_slot'] as int,
      hyakuryuSlot: json['hyakuryu_slot'] as int,
      fireResistance: json['fire_resistance'] as int,
      waterResistance: json['water_resistance'] as int,
      lightningResistance: json['lightning_resistance'] as int,
      iceResistance: json['ice_resistance'] as int,
      dragonResistance: json['dragon_resistance'] as int,
      grade: json['grade'] as int,
      createdAt: DateTime.parse(json['created_at'] as String).toLocal(),
      updatedAt: DateTime.parse(json['updated_at'] as String).toLocal()
  );

  // factory Pokemon.fromJson(Map<String, dynamic> json) {
  //   List<String> typesToList(dynamic types) {
  //     List<String> ret = [];
  //     for (int i = 0; i < types.length; i++) {
  //       ret.add(types[i]['type']['name']);
  //     }
  //     return ret;
  //   }
  //
  //   return Pokemon(
  //     id: json['id'],
  //     name: json['name'],
  //     types: typesToList(json['types']),
  //     imageUrl: json['sprites']['other']['official-artwork']['front_default'],
  //   );
  // }

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'id': id,
      'armorName': armorName,
      'firstSkillId': firstSkillId,
      'firstSkillName': firstSkillName,
      'firstSkillLevel': firstSkillLevel,
      'secondSkillId': secondSkillId,
      'secondSkillName': secondSkillName,
      'secondSkillLevel': secondSkillLevel,
      'thirdSkillId': thirdSkillId,
      'thirdSkillName': thirdSkillName,
      'thirdSkillLevel': thirdSkillLevel,
      'fourthSkillId': fourthSkillId,
      'fourthSkillName': fourthSkillName,
      'fourthSkillLevel': fourthSkillLevel,
      'fifthSkillId': fifthSkillId,
      'fifthSkillName': fifthSkillName,
      'fifthSkillLevel': fifthSkillLevel,
      'minDefensePower': minDefensePower,
      'maxDefensePower': maxDefensePower,
      'part': part,
      'firstSlot': firstSlot,
      'secondSlot': secondSlot,
      'thirdSlot': thirdSlot,
      'hyakuryuSlot': hyakuryuSlot,
      'fireResistance': fireResistance,
      'waterResistance': waterResistance,
      'lightningResistance': lightningResistance,
      'iceResistance': iceResistance,
      'dragonResistance': dragonResistance,
      'grade': grade,
      'createdAt': createdAt.toUtc().toIso8601String(),
      'updatedAt': updatedAt.toUtc().toIso8601String()
    };
  }

  Map<String, dynamic> toCreateMap() {
    List<int> slotList = [firstSlot, secondSlot, thirdSlot];
    slotList.sort((a, b) => b.compareTo(a));
    return <String, dynamic>{
      'id': id,
      'armorName': armorName,
      'firstSkillId': firstSkillId,
      'firstSkillName': firstSkillName,
      'firstSkillLevel': firstSkillLevel,
      'secondSkillId': secondSkillId,
      'secondSkillName': secondSkillName,
      'secondSkillLevel': secondSkillLevel,
      'thirdSkillId': thirdSkillId,
      'thirdSkillName': thirdSkillName,
      'thirdSkillLevel': thirdSkillLevel,
      'fourthSkillId': fourthSkillId,
      'fourthSkillName': fourthSkillName,
      'fourthSkillLevel': fourthSkillLevel,
      'fifthSkillId': fifthSkillId,
      'fifthSkillName': fifthSkillName,
      'fifthSkillLevel': fifthSkillLevel,
      'minDefensePower': minDefensePower,
      'maxDefensePower': maxDefensePower,
      'part': part,
      'firstSlot': slotList[0],
      'secondSlot': slotList[1],
      'thirdSlot': slotList[2],
      'hyakuryuSlot': hyakuryuSlot,
      'fireResistance': fireResistance,
      'waterResistance': waterResistance,
      'lightningResistance': lightningResistance,
      'iceResistance': iceResistance,
      'dragonResistance': dragonResistance,
      'grade': grade,
      'createdAt': DateTime.now().toUtc().toIso8601String(),
      'updatedAt': DateTime.now().toUtc().toIso8601String()
    };
  }

  Map<String, dynamic> toUpdateMap() {
    List<int> slotList = [firstSlot, secondSlot, thirdSlot];
    slotList.sort((a, b) => b.compareTo(a));
    return <String, dynamic>{
      'id': id,
      'armorName': armorName,
      'firstSkillId': firstSkillId,
      'firstSkillName': firstSkillName,
      'firstSkillLevel': firstSkillLevel,
      'secondSkillId': secondSkillId,
      'secondSkillName': secondSkillName,
      'secondSkillLevel': secondSkillLevel,
      'thirdSkillId': thirdSkillId,
      'thirdSkillName': thirdSkillName,
      'thirdSkillLevel': thirdSkillLevel,
      'fourthSkillId': fourthSkillId,
      'fourthSkillName': fourthSkillName,
      'fourthSkillLevel': fourthSkillLevel,
      'fifthSkillId': fifthSkillId,
      'fifthSkillName': fifthSkillName,
      'fifthSkillLevel': fifthSkillLevel,
      'minDefensePower': minDefensePower,
      'maxDefensePower': maxDefensePower,
      'part': part,
      'firstSlot': slotList[0],
      'secondSlot': slotList[1],
      'thirdSlot': slotList[2],
      'hyakuryuSlot': hyakuryuSlot,
      'fireResistance': fireResistance,
      'waterResistance': waterResistance,
      'lightningResistance': lightningResistance,
      'iceResistance': iceResistance,
      'dragonResistance': dragonResistance,
      'grade': grade,
      'createdAt': createdAt.toUtc().toIso8601String(),
      'updatedAt': DateTime.now().toUtc().toIso8601String()
    };
  }

  static List<Armor> someArmors = [
    Armor(
        armorName: "頭なし",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.head],
        firstSlot: 0,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "胴なし",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.torso],
        firstSlot: 0,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "腕なし",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.arm],
        firstSlot: 0,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "腰なし",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.waist],
        firstSlot: 0,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "脚なし",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.leg],
        firstSlot: 0,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "頭スロ1-0-0",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.head],
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "胴スロ1-0-0",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.torso],
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "腕スロ1-0-0",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.arm],
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "腰スロ1-0-0",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.waist],
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "脚スロ1-0-0",
        minDefensePower: 0,
        maxDefensePower: 0,
        part: ArmorPartExtension.armorParts[ArmorPart.leg],
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 0,
        waterResistance: 0,
        lightningResistance: 0,
        iceResistance: 0,
        dragonResistance: 0,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "ぼーんヘルム",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.head],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 1,
        secondSkillId: 2,
        secondSkillName: "防御",
        secondSkillLevel: 2,
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 1,
        fireResistance: 5,
        waterResistance: -3,
        lightningResistance: 3,
        iceResistance: 0,
        dragonResistance: -5,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "ぼーんメイル",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.torso],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 2,
        secondSkillId: 2,
        secondSkillName: "反動軽減",
        secondSkillLevel: 1,
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 5,
        waterResistance: -3,
        lightningResistance: 3,
        iceResistance: 0,
        dragonResistance: -5,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "ぼーんアーム",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.arm],
        firstSkillId: 1,
        firstSkillName: "反動軽減",
        firstSkillLevel: 2,
        secondSkillId: 2,
        secondSkillName: "気絶耐性",
        secondSkillLevel: 1,
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 5,
        waterResistance: -3,
        lightningResistance: 3,
        iceResistance: 0,
        dragonResistance: -5,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "ぼーんコイル",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.waist],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 2,
        secondSkillId: 2,
        secondSkillName: "気絶耐性",
        secondSkillLevel: 2,
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 5,
        waterResistance: -3,
        lightningResistance: 3,
        iceResistance: 0,
        dragonResistance: -5,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "ぼーんグリーヴ",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.leg],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 2,
        secondSkillId: 2,
        secondSkillName: "防御",
        secondSkillLevel: 5,
        firstSlot: 1,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 0,
        fireResistance: 5,
        waterResistance: -3,
        lightningResistance: 3,
        iceResistance: 0,
        dragonResistance: -5,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "はんたーヘルム",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.head],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 1,
        secondSkillId: 2,
        secondSkillName: "防御",
        secondSkillLevel: 1,
        firstSlot: 2,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 1,
        fireResistance: 2,
        waterResistance: 2,
        lightningResistance: 2,
        iceResistance: 2,
        dragonResistance: 2,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "はんたーメイル",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.torso],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 1,
        secondSkillId: 2,
        secondSkillName: "防御",
        secondSkillLevel: 1,
        firstSlot: 2,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 1,
        fireResistance: 2,
        waterResistance: 2,
        lightningResistance: 2,
        iceResistance: 2,
        dragonResistance: 2,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "はんたーアーム",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.arm],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 1,
        secondSkillId: 2,
        secondSkillName: "防御",
        secondSkillLevel: 1,
        firstSlot: 2,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 1,
        fireResistance: 2,
        waterResistance: 2,
        lightningResistance: 2,
        iceResistance: 2,
        dragonResistance: 2,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "はんたーコイル",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.waist],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 1,
        secondSkillId: 2,
        secondSkillName: "防御",
        secondSkillLevel: 1,
        firstSlot: 2,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 1,
        fireResistance: 2,
        waterResistance: 2,
        lightningResistance: 2,
        iceResistance: 2,
        dragonResistance: 2,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
    Armor(
        armorName: "はんたーグリーヴ",
        minDefensePower: 5,
        maxDefensePower: 50,
        part: ArmorPartExtension.armorParts[ArmorPart.leg],
        firstSkillId: 1,
        firstSkillName: "攻撃",
        firstSkillLevel: 1,
        secondSkillId: 2,
        secondSkillName: "防御",
        secondSkillLevel: 1,
        firstSlot: 2,
        secondSlot: 0,
        thirdSlot: 0,
        hyakuryuSlot: 1,
        fireResistance: 2,
        waterResistance: 2,
        lightningResistance: 2,
        iceResistance: 2,
        dragonResistance: 2,
        grade: ArmorGradeExtension.armorGrades[ArmorGrade.none],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now()
    ),
  ];
}